name: Telegram Bot CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run and Kill
      run: |
        python inline_bot.py &
        sleep 10
        kill $!

